# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone_code', models.IntegerField()),
                ('phone_length_without_code', models.IntegerField()),
                ('from_address_check', models.BooleanField()),
                ('to_address_check', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('whois_code', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='city_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.CityGroup'),
        ),
    ]
