# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-08 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='taxi_phone',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
