# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_city_taxi_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='group_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='tarif',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
