# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20161209_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_center_lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='city_center_lng',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='city_zoom',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
