# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20161214_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='main_in_group',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
