# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_city_main_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_for_select',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
