# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_city_name_for_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='brigadier_phone',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
