# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-05 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_blackphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='brigadier_phone',
            new_name='day_brigadier_phone',
        ),
    ]
