# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-07 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20171015_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_group',
        ),
        migrations.RemoveField(
            model_name='city',
            name='main_in_group',
        ),
    ]
